# Generated by Django 3.2.18 on 2023-04-05 13:47

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xb_promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('section_number', models.IntegerField()),
                ('article', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=80)),
                ('section_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('feature_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='xb_promo.featurepage')),
            ],
        ),
    ]
