# Generated by Django 3.2.18 on 2023-04-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_promo', '0002_featuresection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresection',
            options={'ordering': ['feature_page', 'section_number']},
        ),
    ]
