# Generated by Django 3.2.18 on 2023-04-10 13:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xb_promo', '0003_alter_featuresection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField()),
                ('description', models.CharField(max_length=240)),
                ('keywords', models.CharField(max_length=240)),
                ('content', models.TextField()),
                ('screenshot_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_issue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField()),
                ('content', models.TextField()),
                ('screenshot_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
                ('related_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_answer', to='xb_promo.issues')),
            ],
            options={
                'ordering': ['related_issue', 'priority', 'date_submitted'],
            },
        ),
    ]
