# Generated by Django 3.2.18 on 2023-04-13 17:27

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_promo', '0007_issue_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
