# Generated by Django 3.2.18 on 2023-04-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_promo', '0009_alter_issue_screenshot_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['related_issue', 'priority', '-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['priority', '-date_submitted']},
        ),
    ]
