# Generated by Django 3.2.18 on 2023-05-03 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_promo', '0010_auto_20230421_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='screenshot_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
